name: Validate Pull Request

on: [pull_request]

jobs:
  validate:
    uses: jco-digital/jcore-module-actions/.github/workflows/pull.yml@v1.0.0

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build project
        run: make

      - name: Commit built blocks
        uses: EndBug/add-and-commit@v9
        with:
          add: 'blocks/build'
          message: 'chore(blocks): build blocks for release'
          default_author: github_actions
      
